# Example configuration for ChatHistoryManager
chat_history_manager:
  # Type of implementation to use
  type: DefaultChatHistoryManager
  
  # Storage configuration
  storage:
    # Available types: json, database
    type: json
    
    # JSON storage configuration (used if type is 'json')
    json_config:
      # Base directory where chat files will be stored
      base_path: ./chats
      # Optional: Set permissions for newly created files (default is 0600)
      file_permissions: 0600
      # Optional: Enable directory structure for large deployments (creates subdirectories)
      use_subdirectories: true
    
    # Database storage configuration (used if type is 'database')
    database_config:
      # Connection string or path to database
      connection: sqlite:///chats.db
      # Table names (optional, defaults shown below)
      tables:
        chats_table: chats
        messages_table: messages
  
  # General configuration
  config:
    # Default number of messages to retrieve when getting history
    default_message_limit: 20
    
    # Maximum messages to keep per chat (oldest will be pruned)
    # Set to 0 for unlimited (not recommended for production)
    max_messages_per_chat: 1000
    
    # Data retention policy (in days, 0 means keep forever)
    retention_days: 90
    
    # Auto-title generation
    title_generation:
      # Enable automatic title generation for new chats
      enabled: true
      # Number of message exchanges before generating a title
      # (a value of 2 means after 2 user messages and 2 assistant responses)
      exchanges_before_title: 2
      # Whether to use the LLM (generator) for title creation
      # If false, will use simple concatenation of first user message
      use_llm: true
      # Maximum length of generated titles
      max_length: 50

# Example of ChatHistoryManager integration in Orchestrator config
orchestrator:
  type: DefaultOrchestrator
  config:
    # ... other orchestrator config ...
    
    # Chat history configuration for Orchestrator
    chat_history:
      # Whether to create a new chat if chat_id is not provided
      create_new_chat_if_missing: true
      # Whether to use the most recent chat if none specified
      use_most_recent_if_missing: true
      # Number of messages to include in prompt context
      context_message_limit: 10
      # Whether to asynchronously generate titles for new chats
      async_title_generation: true 